export const SET_ERROR = "SET_ERRORS";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const GET_FEATURE = "GET_FEATURE";
export const GET_PROFILE = "GET_PROFILE";
export const REGISTER_USER_WITH_EMAIL = "REGISTER_USER_WITH_EMAIL";
export const LOGIN_USER_WITH_EMAIL = "LOGIN_USER_WITH_EMAIL";
